version: "3.8"

services:
  mongo:
    image: mongo:7
    container_name: mongo-db
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME:-root}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD:-example}
    volumes:
      - mongo-data:/data/db
    networks:
      - mongo-net

  mongo-express:
    image: mongo-express:1.0.2-20
    container_name: mongo-express
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_INITDB_ROOT_USERNAME:-root}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_INITDB_ROOT_PASSWORD:-example}
      ME_CONFIG_MONGODB_SERVER: mongo-db
    depends_on:
      - mongo
    networks:
      - mongo-net

  mongo-simple-app:
    build: .
    container_name: mongo-simple-app
    restart: unless-stopped
    environment:
      - MONGO_URL=mongodb://root:example@mongo-db:27017
      - DB_NAME=testdb
      - COLLECTION=users
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    networks:
      - mongo-net

volumes:
  mongo-data:

networks:
  mongo-net:
    driver: bridge
