# app-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-simple-app
  namespace: mongo-demo
  labels:
    app: mongo-simple-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-simple-app
  template:
    metadata:
      labels:
        app: mongo-simple-app
    spec:
      containers:
      - name: mongo-simple-app
        image: ivykiera/fullstack-mongo-k8s-demo-mongo-simple-app
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 256Mi
        env:
        - name: MONGO_USER
          valueFrom:
            secretKeyRef:
              name: app-db-credentials
              key: MONGO_USER
        - name: MONGO_PASS
          valueFrom:
            secretKeyRef:
              name: app-db-credentials
              key: MONGO_PASS
        - name: DB_NAME
          value: testdb
        - name: COLLECTION
          value: users
        - name: MONGO_URL
          value: mongodb://$(MONGO_USER):$(MONGO_PASS)@mongo:27017/testdb?authSource=admin
        readinessProbe:
          tcpSocket:
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 2
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 15
          periodSeconds: 20
          timeoutSeconds: 2
