apiVersion: v1
kind: Service
metadata:
  name: mongo-simple-app
  namespace: mongo-demo
spec:
  type: NodePort
  selector:
    app: mongo-simple-app
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30000
