apiVersion: v1
kind: Service
metadata:
  name: mongo-express
  namespace: mongo-demo
spec:
  type: NodePort
  selector:
    app: mongo-express
  ports:
    - port: 8081
      targetPort: 8081
      nodePort: 30081
