# NEW: mongo-express-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: mongo-express-auth
  namespace: mongo-demo
type: Opaque
stringData:
  ME_CONFIG_BASICAUTH_USERNAME: meadmin
  ME_CONFIG_BASICAUTH_PASSWORD: s3cret
