# mongo-express-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: mongo-express
  namespace: mongo-demo
  labels:
    app: mongo-express
spec:
  selector:
    app: mongo-express
  ports:
  - name: http
    port: 8081
    targetPort: 8081
    nodePort: 30081
    protocol: TCP
  type: NodePort
